<a href="https://colab.research.google.com/github/DarkLight0418/bdai_class/blob/main/20260912_%EC%88%98%EC%97%85_%EC%A0%84_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list_a = [1, 2, 3, 4, 5]
list_b = ['a', 'b', 'c', 'd', 'e']

print(list_a)
print(list_b)

[1, 2, 3, 4, 5]
['a', 'b', 'c', 'd', 'e']

In [ ]:
print(list(range(50, 0, -4)))

[50, 46, 42, 38, 34, 30, 26, 22, 18, 14, 10, 6, 2]

In [ ]:
a = [23, 3, 16, 45, 11]
print(a[0], a[3])
print(a[-1], a[-3])

23 45
11 16

In [ ]:
list_hangeul = ['가', '나', '다', '라', '마', '바', '사']

In [ ]:
list_hangeul = ['가', '나', '다', '라', '마', '바', '사']

print(list_hangeul[3])
print(list_hangeul[0:3])
print(list_hangeul[5:])

라
['가', '나', '다']
['바', '사']

In [ ]:
a = [23, 3, 16, 45, 11]

a.append(99)
print(a)

[23, 3, 16, 45, 11, 99]

In [ ]:
a = [23, 3, 16, 45, 11]

a = a + [99]
print(a)

[23, 3, 16, 45, 11, 99]

In [ ]:
a = [23, 3, 16, 45, 11]

del a[2]
print(a)

[23, 3, 45, 11]

In [ ]:
a = [23, 3, 16, 45, 11]

a.remove(45)
print(a)

[23, 3, 16, 11]

In [ ]:
list1 = [1, 3, 5, 7]
list2 = [2, 4, 8]

list2.append(list1[1])
print(list2)

[2, 4, 8, 3]

In [ ]:
del list2[2]

print(list2)

[2, 40, 3]

In [ ]:
list2[1] = list2[1] * 10

print(list2)

[2, 40, 8, 3]

In [ ]:
dict_a = {  'v1' : 32,
            'l1' : [1, 2, 3],
            'd1' : {'a' :1, 'b' :2} }

print(dict_a)
dict_a.items()

{'v1': 32, 'l1': [1, 2, 3], 'd1': {'a': 1, 'b': 2}}

dict_items([('v1', 32), ('l1', [1, 2, 3]), ('d1', {'a': 1, 'b': 2})])

In [ ]:
print( dict_a['v1'])
print('=' * 30)

print( dict_a['l1'])
print( dict_a['l1'][:2])
print('=' * 30)

print( dict_a['d1'])
print( dict_a['d1']['a'])

32
==============================
[1, 2, 3]
[1, 2]
==============================
{'a': 1, 'b': 2}
1

In [ ]:
member = {'name': ['한기영'], 'age': [49], 'gender': ['m']}

In [ ]:
member['name2'] = ['김한재']
member['age2'] = [27]
member['gender2'] = ['m']

print(member)

{'name': ['한기영'], 'age': [49], 'gender': ['m'], 'name2': ['김한재'], 'age2': [27], 'gender2': ['m']}

In [ ]:
print(member['age'] + member['age2'])
print(member['age'][0])

[49, 27]
49

In [ ]:
import pandas as pd

In [ ]:
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic_simple.csv'
data = pd.read_csv(path)

data.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,7.2500,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,7.9250,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,Southampton
4,5,0,3,"Allen, Mr. William Henry",male,35.0,8.0500,Southampton
5,6,0,3,"Moran, Mr. James",male,NaN,8.4583,Queenstown
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,51.8625,Southampton
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,21.0750,Southampton
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,11.1333,Southampton
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,30.0708,Cherbourg

In [ ]:
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/Attrition_simple2.CSV'
data = pd.read_csv(path)
data.head(5)

,Attrition,Age,Department,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany
0,0,33,Research & Development,7,3,817,3,Male,3,Married,11691,0,No,11,0,14,3,4,13
1,0,35,Research & Development,18,2,1412,3,Male,4,Single,9362,2,No,11,0,10,2,3,2
2,0,42,Research & Development,6,3,1911,3,Male,1,Married,13348,9,No,13,1,18,3,4,13
3,0,46,Sales,2,3,1204,3,Female,1,Married,17048,8,No,23,0,28,2,3,26
4,1,22,Research & Development,4,1,593,3,Male,3,Single,3894,5,No,16,0,4,3,3,2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

path2 = '/content/drive/MyDrive/airquality_simple.csv'
home = pd.read_csv(path2)

home.head(5)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

   Ozone  Solar.R  Wind  Temp  Month  Day
0     41    190.0   7.4    67      5    1
1     36    118.0   8.0    72      5    2
2     12    149.0  12.6    74      5    3
3     18    313.0  11.5    62      5    4
4     19      NaN  14.3    56      5    5

In [ ]:
path3 = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/Attrition_simple2.CSV'
data3 = pd.read_csv(path3)

data3.head(5)

,Attrition,Age,Department,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany
0,0,33,Research & Development,7,3,817,3,Male,3,Married,11691,0,No,11,0,14,3,4,13
1,0,35,Research & Development,18,2,1412,3,Male,4,Single,9362,2,No,11,0,10,2,3,2
2,0,42,Research & Development,6,3,1911,3,Male,1,Married,13348,9,No,13,1,18,3,4,13
3,0,46,Sales,2,3,1204,3,Female,1,Married,17048,8,No,23,0,28,2,3,26
4,1,22,Research & Development,4,1,593,3,Male,3,Single,3894,5,No,16,0,4,3,3,2

In [ ]:
data3.tail(3)

,Attrition,Age,Department,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany
1172,0,29,Research & Development,9,3,1558,3,Male,3,Married,2451,6,No,18,2,5,2,2,1
1173,0,29,Sales,2,3,469,4,Male,3,Married,4649,1,No,14,1,4,3,2,4
1174,0,43,Sales,16,3,327,4,Female,4,Married,16064,5,Yes,22,1,22,3,3,17

In [ ]:
data3.shape

(1175, 19)

In [ ]:
print(data3.columns)

Index(['Attrition', 'Age', 'Department', 'DistanceFromHome', 'Education',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany'],
      dtype='object')

In [ ]:
list(data3)

['Attrition',
 'Age',
 'Department',
 'DistanceFromHome',
 'Education',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'Gender',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'NumCompaniesWorked',
 'OverTime',
 'PercentSalaryHike',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany']

In [ ]:
data3.dtypes

Attrition                   int64
Age                         int64
Department                 object
DistanceFromHome            int64
Education                   int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                     object
JobSatisfaction             int64
MaritalStatus              object
MonthlyIncome               int64
NumCompaniesWorked          int64
OverTime                   object
PercentSalaryHike           int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
dtype: object

In [ ]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Attrition                1175 non-null   int64
 1   Age                      1175 non-null   int64
 2   Department               1175 non-null   object
 3   DistanceFromHome         1175 non-null   int64
 4   Education                1175 non-null   int64
 5   EmployeeNumber           1175 non-null   int64
 6   EnvironmentSatisfaction  1175 non-null   int64
 7   Gender                   1175 non-null   object
 8   JobSatisfaction          1175 non-null   int64
 9   MaritalStatus            1175 non-null   object
 10  MonthlyIncome            1175 non-null   int64
 11  NumCompaniesWorked       1175 non-null   int64
 12  OverTime                 1175 non-null   object
 13  PercentSalaryHike        1175 non-null   int64
 14  StockOptionLevel         1175 non-null   int64
 15  TotalWorkingYears        1175 non-null   int64
 16  TrainingTimesLastYear    1175 non-null   int64
 17  WorkLifeBalance          1175 non-null   int64
 18  YearsAtCompany           1175 non-null   int64
dtypes: int64(15), object(4)
memory usage: 174.5+ KB

# (3) 기본 집계
### 부터 할 차례