<a href="https://colab.research.google.com/github/DarkLight0418/bdai_class/blob/main/%EA%B9%80%ED%95%9C%EC%9E%AC_4578_20260913_02_%E1%84%91%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%8A%E1%85%A5%E1%86%AB%E1%84%80%E1%85%B5%E1%84%8E%E1%85%A9_%E1%84%91%E1%85%A1%E1%86%AB%E1%84%83%E1%85%A1%E1%84%89%E1%85%B3_%E1%84%87%E1%85%A9%E1%86%A8%E1%84%89%E1%85%B3%E1%86%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **파이썬 기초, 판다스 복습**

## **1. 파이썬 기본 자료형**
* 리스트(list)와 딕셔너리(dictionary)

### **(1) 리스트**

* 대괄호 […, …, …, …, … ] 로 선언
    * List_a = [ 1, 2, 3, 4, 5 ]

#### **1) 기본 생성**

In [ ]:
# 리스트 생성하기
list_a = [ 1, 2, 3, 4, 5 ]
list_b = ['a','b','c','d','e']

# 전체 조회 - 두개 다 출력
print(list_a)
print(list_b)

[1, 2, 3, 4, 5]
['a', 'b', 'c', 'd', 'e']

* print문
    * 코드셀 안에서 화면에 결과를 출력하기 위해서 사용
    * 출력할 결과가 1개이면 생략 가능
    * 여러 개이면 반드시 print 문 사용해야 함
* 대체가능한 함수 : display()

#### **2) range 함수**
* range 함수는 자주 사용됩니다.
    * 순차 증가값(등차행렬)으로 리스트 생성시
* 문법 : range(시작값, 끝값, 증가값)
    * 시작값 생략 --> 0부터 시작
    * 증가값 생략 --> 1씩 증가
    * 끝값 : 포함 안됨, 이전까지

In [ ]:
# 1부터 11까지, 2씩 증가하는 값으로 리스트 생성
range(1, 12, 2)

In [ ]:
list(range(1, 12, 2))

[1, 3, 5, 7, 9, 11]

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 50부터 0 전까지 4씩 감소시킨 값을 리스트로 저장하고 출력하시오.

In [ ]:
list(range(50, 0, -4))

[50, 46, 42, 38, 34, 30, 26, 22, 18, 14, 10, 6, 2]

#### **3) 조회**

* 인덱스로 조회하기
    * 인덱스 : 0부터 시작
    * 인덱스의 끝에서부터 셀 때 : -1, -2, 3, ...

In [ ]:
a = [23, 3, 16, 45, 11]
print(a[0], a[3])
print(a[-1], a[-3])

23 45
11 16

* 인덱스 범위 조회(슬라이싱)
    * 리스트[시작인덱스:끝인덱스]
        * 시작인덱스 부터 **끝 인덱스 전까지**
        * 시작인덱스 생략 ==> 처음부터
        * 끝인덱스 생략 ==> 끝까지

In [ ]:
a = [23, 3, 16, 45, 11]

print(a[0:3])
# 또는
print(a[:3])

In [ ]:
print(a[2:5])
print(a[2:])
print(a[-3:])

[16, 45, 11]
[16, 45, 11]
[16, 45, 11]

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음 항목들로 리스트 '한글'를 생성하시오
* '가','나','다','라','마','바','사'

In [ ]:
한글 = ['가', '나', '다', '라', '마', '바', '사']

[문2] 다음을 출력하시오.
* '라'
* ['가','나',다']
* ['바','사']

In [ ]:
print(한글[3])
print(한글[0:3])
print(한글[5:])

라
['가', '나', '다']
['바', '사']

#### **4) 리스트 수정**

* 값 추가
    * 값을 추가하는 두가지 방법
        * ① .append()
        * ② 리스트 + [추가할 값] : 리스트1 + 리스트2 = 합쳐진 리스트

In [ ]:
a = [23, 3, 16, 45, 11]

a.append(99)
print(a)

In [ ]:
a = [23, 3, 16, 45, 11]

a = a + [99]
print(a)

* 값 수정
    * 인덱스로 해당 값을 조회하고 그 자리에 수정
        * a[2] = 34

In [ ]:
a = [23, 3, 16, 45, 11]

a[2] = 34
print(a)

* 값 삭제
    * 인덱스로 조회한 대상을 삭제 : del a[2]

In [ ]:
a = [23, 3, 16, 45, 11]

del a[2]
print(a)

* 특정 값을 찾아서 삭제 :
    * 리스트.remove(값)

In [ ]:
a = [23, 3, 16, 45, 11]

a.remove(45)
print(a)

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 리스트 list1에 1, 3, 5, 7을, 리스트 list2에 2, 4, 8을 저장하고,
list1의 두 번째 값을 list2에 추가하시오.

In [ ]:
list1 = [1, 3, 5, 7]
list2 = [2, 4, 8]

list2.append(list1[1])
print(list2)

[문2] 문1의 list2에서 세번째 값을 삭제하시오.

In [ ]:
del list2[2]

print(list2)

[문3] 문2의 list2에서 두번째 값에 10을 곱한 값으로 변경하시오.

In [ ]:
list2[1] = list2[1] * 10

print(list2)

### **(2) 딕셔너리(dictionary)**

* 하나의 딕셔너리 안에 다양한 형태의 여러 값들을 저장
* 여러 자료형들의 묶음

#### **1) 생성**

* 중괄호 {} 안에 , key : value 형태로 선언합니다.
    * Value : 다양한 형태의 변수
    * Key : Value 변수의 이름

In [ ]:
dict_a = { 'v1' : 32,
           'l1' : [1, 2, 3],
           'd1' : {'a' : 1, 'b' : 2} }
print(dict_a)

* 딕셔너리 정보 조회
    * .keys() : 딕셔너리의 key 만 조회
    * .values() : 딕셔너리의 값 만 조회
    * .items() : key와 값을 쌍(tuple)으로 조회

In [ ]:
dict_a.keys()

In [ ]:
dict_a.values()

In [ ]:
dict_a.items()

#### **2) 조회**

* 조회시 키로 값을 조회
    * 딕셔너리[키]

In [ ]:
dict_a = { 'v1': 32, 'l1': [1,2,3], 'd1': {'a':1, 'b':2}}

print( dict_a['v1'])
print('=' * 30)

print( dict_a['l1'])
print( dict_a['l1'][:2])
print('=' * 30)

print( dict_a['d1'])
print( dict_a['d1']['a'])

#### **3) 수정**

In [ ]:
dict_a = { 'v1': 32, 'l1': [1,2,3], 'd1': {'a':1, 'b':2}}

In [ ]:
# 추가
dict_a['v2'] = 500
print(dict_a)

In [ ]:
# 수정
dict_a['v2'] = 300
print(dict_a)

In [ ]:
# 삭제
del dict_a['v2']
print(dict_a)

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음 항목으로 딕셔너리를 생성하시오.
* dict name : member
* key : value
    * 'name':['한기영']
    * 'age':[49]
    * 'gender':['m']

In [ ]:
member = {'name': ['한기영'], 'age': [49], 'gender': ['m']}

[문2] member 딕셔너리의 key에 맞게 자신의 정보를 추가해 봅시다.

In [ ]:
member['name2'] = ['김한재']
member['age2'] = [27]
member['gender2'] = ['m']

print(member)

[문3] 다음을 조회해 봅시다.
* [49, ##]
* 49

In [ ]:
print(member['age'] + member['age2'])
print(member['age'][0])

## **2. 데이터프레임**

In [5]:
import pandas as pd

### (1) CSV파일 읽어오기

- 분석용 데이터는 대부분 파일에서 읽어 가져오니 잘 익혀야 할 기능입니다.
- **read_csv()** 함수를 사용해서 CSV 파일에서 데이터를 읽어옵니다.

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic_simple.csv'
data = pd.read_csv(path)

# 상위 10행만 확인
data.head(10)

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 아래 주어진 경로의 파일에서 데이터를 읽어와 데이터프레임 temp 만들어 보세요.

- 파일 경로: 'https://raw.githubusercontent.com/DA4BAM/dataset/master/Attrition_simple2.CSV'

**[Attrition 데이터 셋 정보]**

|	구분	|	변수 명	|	내용	|	type	|	비고	|
|----|----|----|----|----|
|	**Target**	|	**Attrition**	|	이직여부, Yes , No	|	범주	| 1- 이직, 0- 잔류		|
|	feature	|	Age	|	나이	|	숫자	|		|
|	feature	|	DistanceFromHome	|	집-직장 거리	|	숫자	|	마일	|
|	feature	|	EmployNumber	|	사번	|	숫자	| 	|
|	feature	|	Gender	|	성별	|	범주	| Male, Female		|
|	feature	|	JobSatisfaction	|	직무 만족도	|	범주	|	1 Low, 2 Medium, 3 High, 4 Very High	|
|	feature	|	MaritalStatus	|	결혼상태	|	범주	| Single, Married, Divorced		|
|	feature	|	MonthlyIncome	|	월급	|	숫자	| 달러	|
|	feature	|	OverTime	|	야근여부	|	범주	|	Yes, No	|
|	feature	|	PercentSalaryHike	|	전년대비 급여인상율	|	숫자	|	%	|
|	feature	|	TotalWorkingYears	|	총 경력 연수	|	숫자	|		|

In [ ]:
# 데이터 읽어오기
path3 = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/Attrition_simple2.CSV'
data2 = pd.read_csv(path3)

# 상위 5개 확인
data2.head(5)

[문2] csv file로부터 읽어옵시다.

- 파일 이름 : 'airquality_simple.csv'
- 파일을 home directory로 복사해 넣고 읽어 옵니다.

**[airquality_simple 데이터 셋 정보]**

- Ozone : 오존농도
- Solar.R: 태양복사열
- Wind: 풍속
- Temp: 기온
- Month: 월
- Day: 일

In [6]:
# 데이터 읽어오기
path2 = 'airquality_simple.csv'
home = pd.read_csv(path2)

# 상위 5개 확인
home.head(5)

   Ozone  Solar.R  Wind  Temp  Month  Day
0     41    190.0   7.4    67      5    1
1     36    118.0   8.0    72      5    2
2     12    149.0  12.6    74      5    3
3     18    313.0  11.5    62      5    4
4     19      NaN  14.3    56      5    5

### **(2) 데이터프레임 탐색**

- 파일에서 불러온 데이터의 크기, 내용, 분포, 누락된 값 등을 확인할 수 있어야 합니다.
- 확인된 내용을 통해 데이터 전처리 필요 여부를 결정합니다.
- 데이터를 알아야 데이터를 분석할 수 있습니다.

* Attrition 데이터 불러오기

**[Attrition 데이터 셋 정보]**

|	구분	|	변수 명	|	내용	|	type	|	비고	|
|----|----|----|----|----|
|	**Target**	|	**Attrition**	|	이직여부, Yes , No	|	범주	| 1- 이직, 0- 잔류		|
|	feature	|	Age	|	나이	|	숫자	|		|
|	feature	|	DistanceFromHome	|	집-직장 거리	|	숫자	|	마일	|
|	feature	|	EmployNumber	|	사번	|	숫자	| 	|
|	feature	|	Gender	|	성별	|	범주	| Male, Female		|
|	feature	|	JobSatisfaction	|	직무 만족도	|	범주	|	1 Low, 2 Medium, 3 High, 4 Very High	|
|	feature	|	MaritalStatus	|	결혼상태	|	범주	| Single, Married, Divorced		|
|	feature	|	MonthlyIncome	|	월급	|	숫자	| 달러	|
|	feature	|	OverTime	|	야근여부	|	범주	|	Yes, No	|
|	feature	|	PercentSalaryHike	|	전년대비 급여인상율	|	숫자	|	%	|
|	feature	|	TotalWorkingYears	|	총 경력 연수	|	숫자	|		|

In [ ]:
# 데이터 읽어오기
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/Attrition_simple2.CSV'
data = pd.read_csv(path)

# 상위 5개 확인
data.head(5)

**[참고] 자주 사용할 만한 메서드(함수)와 속성들**
- head(): 상위 데이터 확인
- tail(): 하위 데이터 확인
- shape: 데이터프레임 크기
- values: 값 정보 확인(저장하면 2차원 numpy 배열이 됨)
- columns: 열 정보 확인
- dtypes: 열 자료형 확인
- info(): 열에 대한 상세한 정보 확인
- describe(): 기초통계정보 확인

#### **1) 상위, 하위 일부 데이터, 크기 확인**

- **head(*n*), tail(*n*)** 메소드를 사용해 앞 뒤 데이터를 확인합니다.
- 개수를 지정하지 않으면 기본적으로 5개 행이 조회됩니다.

* 상위 데이터 확인

In [ ]:
# 상위 10개 행 데이터
data.head(10)

* 하위 데이터 확인

In [ ]:
# 하위 3개 행 데이터
data.tail(3)

* 크기 확인 .shape

    - **(rows, cols)** 값을 갖는 **튜플** 형태로 확인이 가능합니다.
    - 데이터를 분석할 때 처리할 **데이터 양을 확인**하는 목적으로 많이 사용 합니다.

In [ ]:
# 행 수와 열 수 확인
data.shape

#### **2) 열, 행 정보 보기**

* 열 확인

In [ ]:
# 열 확인
print(data.columns)

In [ ]:
# 데이터프레임을 리스트 함수에 넣으면 열 이름이 리스트로 반환됨.
list(data)

* 자료형 확인
    - int64: 정수형 데이터(int)
    - float64: 실수형 데이터(float)
    - object: 문자열 데이터(string)

In [ ]:
# 열 자료형 확인
data.dtypes

In [ ]:
# 열 자료형, 값 개수 확인
data.info()

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음 경로의 파일을 읽어와 air 데이터프레임으로 저장하세요.

- 파일 경로: 'https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv'

In [8]:
# 데이터 읽어오기
path4 = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv'

home2 = pd.read_csv(path4)

[문2] 데이터프레임 관련 정보를 확인하세요.

In [9]:
# 상위 데이터 확인
home2.head()

   Ozone  Solar.R  Wind  Temp        Date
0     41    190.0   7.4    67  1973-05-01
1     36    118.0   8.0    72  1973-05-02
2     12    149.0  12.6    74  1973-05-03
3     18    313.0  11.5    62  1973-05-04
4     19      NaN  14.3    56  1973-05-05

In [10]:
# 크기 확인
home2.shape

(153, 5)

In [12]:
# 열 이름 확인
print(home2.columns)
list(home2)

Index(['Ozone', 'Solar.R', 'Wind', 'Temp', 'Date'], dtype='object')

['Ozone', 'Solar.R', 'Wind', 'Temp', 'Date']

In [14]:
# 열 자료형, 값 개수 확인
home2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ozone    153 non-null    int64
 1   Solar.R  146 non-null    float64
 2   Wind     153 non-null    float64
 3   Temp     153 non-null    int64
 4   Date     153 non-null    object
dtypes: float64(2), int64(2), object(1)
memory usage: 6.1+ KB

### **(3) 기본 집계**

- 데이터를 좀더 이해하기 위해 고유값, 합, 평균, 최댓값, 최솟값 등을 확인합니다.

#### **1) 고유값 확인**

- 범주형 열(열이 가진 값이 일정한 값인 경우, 성별, 등급 등)인지 확인할 때 사용합니다.

* 칼럼(시리즈)
    * 데이터프레임에서 1개의 열 형태
    * dataframe['column']

<img src='https://github.com/DA4BAM/image/blob/main/%EC%8B%9C%EB%A6%AC%EC%A6%88,%20%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84.png?raw=true' width=500 align="left"/>

In [ ]:
data['MaritalStatus']

* 고유값 확인 : unique() 메소드로 고유값을 확인하며, 결괏값은 배열 형태가 됩니다.

In [ ]:
# MaritalStatus 열 고유값 확인
print(data['MaritalStatus'].unique())

* 고유값과 개수 확인 : value_counts() 메소드로 고유값과 그 개수를 확인하며, 결괏값은 시리즈 형태가 됩니다.

In [ ]:
# MaritalStatus 열 고유값 개수 확인
print(data['MaritalStatus'].value_counts())

#### **2) 기본 집계 메소드 사용**

- 데이터를 1차 집계 한 후 분석을 진행하는 경우가 많으므로 필히 알아두어야 할 내용입니다.
- 이후에 배우는 Groupby 기능에서 같이 사용됩니다.

In [ ]:
# MonthlyIncome 열 합계 조회
print(data['MonthlyIncome'].sum())

In [ ]:
# MonthlyIncome 열 최댓값 조회
print(data['MonthlyIncome'].max())

In [ ]:
# 'Age', 'MonthlyIncome' 열 평균값 확인
print(data[['Age', 'MonthlyIncome']].mean())

In [ ]:
# 'Age', 'MonthlyIncome' 열 중앙값 확인
print(data[['Age', 'MonthlyIncome']].median())

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

[문1] 다음 경로의 파일을 읽어와 데이터프레임으로 저장하세요.

- 파일 경로: 'https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv'

In [15]:
# 데이터 읽어오기
path3 = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/airquality_simple.csv'

test = pd.read_csv(path3)

[문2] Ozone 최댓값을 확인하세요.

In [16]:
print(test['Ozone'].max())

168

[문3] Temp, Wind 최솟값을 확인하세요.

In [17]:
print(test['Temp'].min())
print(test['Wind'].min())

56
1.7

### **(4) 데이터프레임 조회**

- 보고자 하는 데이터를 즉시 조회할 수 있도록 반복 학습과 실습을 통해 익숙해져야 합니다.
- 데이터프레임을 대상으로 조회하는 방법은 다양합니다.
- 그 중 한 가지 방법을 선택해 일관되게 사용하기를 권고합니다.

#### **1) 특정 열 조회**

- **df.loc[ : , [열 이름1, 열 이름2,...]]** 형태로 조회할 열 이름을 리스트로 지정합니다.
- 열 부분은 생략할 수 있었지만, **행 부분을 생략할 수는 없습니다.**
- 하지만 **df[[열 이름1, 열 이름2,...]]** 형태로 인덱서를 생략함이 일반적입니다.
- 조회할 열이 하나면 리스트 형태가 아니어도 됩니다.

In [ ]:
# Attrition 열 조회 : 시리즈로 조회
data['Attrition']

In [ ]:
# Attrition 열 조회2 : 시리즈로 조회
data.Attrition

In [ ]:
# Attrition, Age 열 조회 : 데이터프레임으로 조회
# 대괄호 안에 또 대괄호로 읽지 마시고, 대괄호 안에 리스트!!!
data[['Attrition', 'Age' ]]

<img src='https://raw.githubusercontent.com/jangrae/img/master/practice_01.png' width=120 align="left"/>

In [ ]:
# PercentSalaryHike 열만 조회

In [ ]:
#  Age, DistanceFromHome, Gender열만 조회

#### **2) 조건으로 조회**

- **dataframe.loc[조건]** 형태로 조건을 지정해 조건에 만족하는 데이터만 조회할 수 있습니다.
- 우선 조건이 제대로 판단이 되는지 확인한 후 그 **조건을 대 괄호 안에** 넣으면 됩니다.

* 단일 조건 조회

In [ ]:
# 조건절(조건문)의 결과는 True, False
data['DistanceFromHome'] > 10

In [ ]:
# DistanceFromHome 열 값이 10 보다 큰 행 조회
data.loc[data['DistanceFromHome'] > 10]

* 여러 조건 조회

    - [ ]안에 조건을 여러개 연결할 때 **and와 or 대신에 &와 |**를 사용해야 합니다.
    - 그리고 각 조건들은 **(조건1) & (조건2)** 형태로 **괄호**로 묶어야 합니다.

In [ ]:
# and로 여러 조건 연결
data.loc[(data['DistanceFromHome'] > 10) & (data['JobSatisfaction'] == 4)]

In [ ]:
# or 조건 : |
data.loc[(data['DistanceFromHome'] > 10) | (data['JobSatisfaction'] == 4)]

* isin()
    - **isin([값1, 값2,..., 값n])**: 값1 또는 값2 또는...값n인 데이터만 조회합니다.
    - 주의 isin(**리스트**) 값들을 리스트 형태로 입력해야 합니다.

In [ ]:
# 값 나열
data.loc[data['JobSatisfaction'].isin([1,4])]

- 위 구문은 다음과 같은 의미를 갖습니다.

In [ ]:
# or 조건
data.loc[(data['JobSatisfaction'] == 1) | (data['JobSatisfaction'] == 4)]

- **between(값1, 값2)**: 값1 ~ 값2까지 범위안의 데이터만 조회합니다.

    * inclusive = 'both' (기본값)
        * 'left', 'right', 'neither'

In [ ]:
# 범위 지정
data.loc[data['Age'].between(25, 30)]

- 위 구문은 다음과 같은 의미를 갖습니다.

In [ ]:
# and 조건
data.loc[(data['Age'] >= 25) & (data['Age'] <= 30)]

#### **3) 조건을 만족하는 행의 일부 열 조회**

- **df.loc[조건, ['열 이름1', '열 이름2',...]]** 형태로 조회할 열을 리스트로 지정합니다. ==> 2차원, 데이터프레임형태로 조회

In [ ]:
# 조건에 맞는 하나의 열 조회
data.loc[data['MonthlyIncome'] >= 10000, ['Age']]

In [ ]:
# 조건에 맞는 여러 열 조회
data.loc[data['MonthlyIncome'] >= 10000, ['Age', 'MaritalStatus', 'TotalWorkingYears']]

## **3. 복습문제**

### **(1) 데이터프레임 기본 조회**

1) pandas 라이브러리를 pd 별칭을 주어 불러오세요.

In [ ]:
# 라이브러리 불러오기

2) read_csv() 함수를 사용해 다음 경로의 파일을 불러와 **titanic** 데이터프레임을 만드세요.

- 파일 경로: https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic_simple.csv

**[titanic_simple 데이터 셋 정보]**

- PassengerId : 승객번호
- Survived : 생존여부(1:생존, 0:사망)
- Pclass : 객실등급(1:1등급, 2:2등급, 3:3등급)
- Name : 승객이름
- Sex : 성별(male, female)
- Age : 나이
- Fare : 운임($)
- Embarked : 승선지역(Southhampton, Cherbourg, Queenstown)

In [ ]:
# 파일 읽어오기

3) head() 메소드로 상위 10개 행 데이터를 확인하세요.

In [ ]:
# 상위 10행 출력

4) shape 속성을 사용해 행과 열의 개수를 확인하세요.

In [ ]:
# 크기 확인

5) dtype 속성을 사용해 각 열의 데이터 형식을 확인하세요.

In [ ]:
# 열 데이터 형식 확인

6) info() 메소드를 사용해 각 열의 값 개수와 데이터 형식 등을 한 번에 확인하세요.

In [ ]:
# 열 정보 확인

7) value_counts() 메소드를 사용해 다음 두 열의 고유값과 그 개수를 각각
확인하세요.

- Embarked
- Pclass

8) Age, Fare 두 열의 최댓값을 한 번에 확인하세요.

9) Fare 열을 기준으로 내림차순 정렬해서 상위 10개를 조회하세요.

### **(2) 데이터프레임 조건 조회**

1. Name 열만 조회하세요.

2. Name, Age, Sex 열만 조회하세요.

3. Name, Age, Sex 열의 상위 10개 행만 확인하세요.

4. 나이가 70세 이상인 탑승객을 조회하시오.

5. Fare(운임)의 평균을 Fare_mean으로 저장하고 그 값을 확인하세요.

6. 평균 운임보다 적게 내고 탑승한 승객을 조회하시오.

7. 승선지역(Embarked)이 'Southhampton', 'Queenstown' 인 승객을 조회하시오.

8. 나이(Age)가 10대(10이상, 20 미만)인 남자 청소년의 평균 운임(Fare)을 구해 봅시다.